In [27]:
import warnings
warnings.filterwarnings('ignore')

In [28]:
import pandas as pd
import numpy as np
import uuid
import random
from datetime import timedelta

open_orders = dict()
event_types = ['order_created', 'order_fulfilled']
periods = [ts for ts in pd.date_range(start='1/1/2008', end='31/12/2018') if random.random()>0.8]

def new_random_order():
    return {
        'order_id': uuid.uuid4(),
        'amount': random.random() * 1000,
        'created_at': random.choice(periods)
    } 

def new_random_event():
    event_type = random.choice(event_types)
    order_info = new_random_order()
    if event_type=='order_created':
        open_orders[order_info['order_id']] = order_info
    else:
        if len(open_orders):
            order_id = random.choice(list(open_orders.keys()))
            order_info = open_orders[order_id]
            order_info['created_at'] = order_info['created_at'] + timedelta(random.randrange(0,180))
        open_orders.pop(order_info['order_id'], None)
        
    return {
        "event_id": uuid.uuid4(),
        "event_type": event_type,
        "order_id": order_info['order_id'],
        "amount": order_info['amount'],
        "created_at": order_info['created_at']
    }

df = pd.DataFrame([new_random_event() for _ in range(0, 100)])
df

,event_id,event_type,order_id,amount,created_at
0,06aefb52-5ce3-422d-a2bf-55af277ff60d,order_created,f398782a-a7a7-49e3-b6b3-202be1242564,64.859159,2008-10-21
1,6fbb6972-e64c-456a-83be-ce8d95720525,order_created,55846aab-53f6-4aa4-94c8-e63c05c4b579,690.585702,2011-10-16
2,a9ec9c6f-dd9c-4476-b7bf-9042feda3ea4,order_fulfilled,55846aab-53f6-4aa4-94c8-e63c05c4b579,690.585702,2011-12-20
3,47017d3b-161e-41df-a609-920321aa3a0d,order_created,6764d3db-be33-40b5-a738-a8c8e197e97b,442.427812,2014-07-07
4,1ee69cdf-ac3a-46d3-a05e-869bf46a3097,order_fulfilled,6764d3db-be33-40b5-a738-a8c8e197e97b,442.427812,2014-12-29
...,...,...,...,...,...
95,0bd1ff12-bae5-40c4-97ae-6a2a68da4ca5,order_created,0b33da16-ad56-4c70-8757-14a13523f98f,766.228320,2010-09-08
96,0d3fb3ec-0e81-414d-b469-d655e79b9344,order_created,f3b6a859-528c-44d1-aee3-88dcec0cc90e,569.196461,2018-12-29
97,50b588b1-6695-49bc-8468-d9c7ebf61b04,order_created,a980e241-87fb-4ccd-9961-ccf64b2b5a16,289.133204,2017-05-17
98,49bc7300-e469-45a4-a9ac-c29b099e0ed8,order_created,5191d773-519a-44a6-a104-42016c120e2c,887.889618,2017-11-20
99,31d8c783-f57d-4508-9f4a-5930af9bda6a,order_fulfilled,f3b6a859-528c-44d1-aee3-88dcec0cc90e,569.196461,2018-12-29

# Q1. List all events with "event_type" as "order_created" where "order_fulfilled" is at least 30 days later than the "order_created" (dates are based on "created_at").

# Q2. Determine the average, minimum, maximum and count delay per month per calendar year where the delay is greater than 30 days.

In [ ]:
# Sample result:

    
# result = [
#     {order_id: "",
#      order_date: "...",
#      fulfilled_date: "...",
#      delay: 30
#     },
#     ...
# ]
# Your code here

'''
Hint:

Filter event type for order created, and order fulfilled then, store them in different dataframes
join the two dataframes together

take the difference of the two datetimes and store in a new column

filter for dates < 30, convert the dataframe to a dictionary

Q2 should be easy for you
'''

In [50]:
# Sample Output

# fulfilled_year  fulfilled_month     mean         min          max       count
# 2008            10                  73.0         70.0         76.0      2

# Your code here

Question #1

In [29]:
#Creating a new dataframe for order_created evet type

created_df = df.loc[ df["event_type"] == "order_created"]

In [30]:
#creating a new dataframe for order_fulfilled event type


fulfilled_df = df.loc[df["event_type"] == "order_fulfilled"]

In [31]:
#Merging both dataframes together to form a new dataframe

merged_df = pd.merge(created_df, fulfilled_df, on = ["order_id", "amount"], how = "inner")

In [32]:
#Getting the time delay i.e fulfilled date - order date


merged_df["delay"] = (merged_df["created_at_y"] - merged_df["created_at_x"]) / np.timedelta64(1, "D")
merged_df["delay"] = merged_df["delay"].astype(int)

merged_df

,event_id_x,event_type_x,order_id,amount,created_at_x,event_id_y,event_type_y,created_at_y,delay
0,06aefb52-5ce3-422d-a2bf-55af277ff60d,order_created,f398782a-a7a7-49e3-b6b3-202be1242564,64.859159,2008-10-21,6d065a75-4393-4b1b-b241-2bc206609d10,order_fulfilled,2008-11-09,19
1,6fbb6972-e64c-456a-83be-ce8d95720525,order_created,55846aab-53f6-4aa4-94c8-e63c05c4b579,690.585702,2011-10-16,a9ec9c6f-dd9c-4476-b7bf-9042feda3ea4,order_fulfilled,2011-12-20,65
2,47017d3b-161e-41df-a609-920321aa3a0d,order_created,6764d3db-be33-40b5-a738-a8c8e197e97b,442.427812,2014-07-07,1ee69cdf-ac3a-46d3-a05e-869bf46a3097,order_fulfilled,2014-12-29,175
3,81977d52-9ae3-41e1-93e5-0c5398c553bd,order_created,64e5dfcf-8c96-458d-9cb8-854dab616bea,934.957777,2010-02-06,fe54cbd3-552e-4444-9f33-360c5036a95d,order_fulfilled,2010-05-13,96
4,2ffcd680-3d3c-49c4-809d-28286073b385,order_created,b772eb8c-a266-44a4-b303-dd49474aaf1d,161.429742,2012-06-02,1490cb06-bacf-428a-aeac-3d6bcb1fc2dd,order_fulfilled,2012-06-05,3
5,499f5df5-dd85-4bfe-bab5-29eaa3ee54f6,order_created,a2662e34-9b64-4168-93d0-f5a0a1be89b0,685.974289,2016-04-23,661337b7-2844-403e-96d6-f0b6cfcd9990,order_fulfilled,2016-09-28,158
6,ab83b43c-c036-4632-9252-981d8c96a305,order_created,b3b450e9-543d-45f4-ad12-dbbc269ed26c,291.575697,2010-07-24,0991a2b9-a1ca-4fa8-b54e-ffc7398636c0,order_fulfilled,2011-01-03,163
7,2a495398-5cd1-4f17-a91b-7a4d454ec4a8,order_created,dc957b8a-d153-47ab-9eaa-fa3c8e5d0fa8,552.729193,2014-10-04,51f16ce7-c6b7-47cf-bf22-b91ffbd61005,order_fulfilled,2014-12-11,68
8,bce89831-2cb3-4c22-843c-e5b7b15cdabc,order_created,013f1f27-f0cd-416b-ad6a-533a126523f6,92.058322,2017-02-05,e1238e52-d6ad-4749-9464-0d88cb1e09c8,order_fulfilled,2017-05-29,113
9,26fbaddb-f67b-4e1f-9249-838d9a586a5d,order_created,92741913-91c1-4968-8a74-d8cd06e995d7,510.871796,2012-06-30,6a5af395-8ce2-4e49-afad-5e0be49faf6f,order_fulfilled,2012-09-01,63
10,d01e39e3-3b24-4276-a0d1-5d47581de75f,order_created,fa6afd8c-2eca-468a-863e-0febae8840bf,560.363852,2015-02-20,0e46bbe0-47f2-42c8-b45c-2b5246852776,order_fulfilled,2015-07-07,137
11,9f269b4a-f7e5-4643-b56f-e143a17e9f0d,order_created,2f10a9e6-f2ec-4e84-8334-ebd6e71ecd71,321.500688,2016-06-16,492a66cc-dc94-481a-8f37-6554e67e429b,order_fulfilled,2016-06-16,0
12,90f8a7e5-2576-49e1-be1b-4651c2abe9e9,order_created,775c1372-4e05-4f61-b828-b5bc03641ceb,745.473292,2011-03-26,f2588ad3-5ecc-44cd-bd44-b80103cd3e89,order_fulfilled,2011-08-18,145
13,8835b499-ad49-4dad-90a7-19d489461a38,order_created,1a0f349f-34fe-426d-8b6b-24f988ab27ff,61.711721,2015-04-27,ea319424-b4d0-443c-a9c0-5b39960d18e4,order_fulfilled,2015-08-19,114
14,bbfe1dac-a755-4f8e-be58-ca236e068397,order_created,b220551f-7eab-42e4-b9a8-a1eb585a3774,297.066306,2010-07-24,55382f50-f931-48e8-b14f-20690abce802,order_fulfilled,2010-10-24,92
15,6479bc0a-eeed-48ec-b1ef-4dd223ae4490,order_created,301da4d9-3e83-4126-98b9-60f0dce81dca,141.341280,2017-04-18,bd30f8b4-ff81-4317-9849-392e0bb90405,order_fulfilled,2017-07-31,104
16,37fcf8ca-fcb9-4c9c-baac-2854335d7639,order_created,c03d7442-5288-4632-81b2-17f9b3d72ed8,608.368809,2015-09-07,c110ede0-4d63-4740-96a5-d81a3c890e00,order_fulfilled,2015-10-04,27
17,2f1df57a-d6a6-4d81-8ff2-1c489f6e9e7a,order_created,0cd159b3-e3ae-41ad-bad8-c5415c3ebdfc,731.729933,2018-06-30,61b7fb7f-cad1-476f-81c0-772e0a75c4d7,order_fulfilled,2018-11-12,135
18,334b3482-5b01-48fe-9d92-52aa9996637e,order_created,3e94ecf4-bac0-421e-bcbf-5af592021702,87.396222,2010-09-28,1d09d724-a786-4d07-a409-402b5e3b592a,order_fulfilled,2011-02-19,144
19,a7870462-7f2e-4de7-b474-7c55a117d306,order_created,68e06b8c-c7eb-4a40-974d-088dd86c95bf,691.589017,2011-11-28,d923dbef-d9c6-4304-9791-f747b2ac4789,order_fulfilled,2012-05-12,166
20,d96c1ba7-0882-4caa-a09f-1b0e6c6a74f1,order_created,32db02ab-ebda-48eb-ad54-c66c6df54ee8,921.851503,2015-03-09,3d754b91-2efd-48b1-a42c-ba655c6e37bc,order_fulfilled,2015-05-29,81
21,0c061cee-e648-4df7-a02c-2fe326059c06,order_created,9d48ae97-9d31-4cb5-b3b0-486a746e6896,603.256122,2013-05-03,cb22a401-851a-4acd-a27c-e0cf003b91ef,order_fulfilled,2013-06-22,50
22,73b191db-f54d-4a76-9fb2-e591fd0d0541,order_created,c530e896-a711-45a1-a76f-65a85aa89d70,667.981182,2008-01-01,217794ed-3c58-43b0-b337-c1c556c475d2,order_fulfilled,2008-06-09,160
23,1a378d6a-206f-4fb3-9484-49e0256aa1c9,order_created,09d1ed6a-420f-40a3-983d-57425cd4b439,944.615675,2009-11-30,61be28f3-4173-41cc-ba1a-8f94aed35b08,order_fulfilled,2010-02-22,84
24,b55e996d-395c-4f20-8226-f0f1f15e840b,order_created,0745a0d1-86c5-4d7e-9d15-4553ee4246e1,706.337718,2017-05-29,3cfe4893-ea9c-4888-aac6-0ca6591d3130,order_fulfilled,2017-06-03,5
25,71e73784-29ef-4f08-9408-134772e278a8,order_created,ba37cf2c-e3c6-465c-bdaf-f4a13ffd1ba1,940.389959,2008-03-01,84255e09-b407-4983-b178-d060d3d33c22,order_fulfilled,2008-03-04,3
26,0f9bd1de-3d89-4477-a900-6b4b4f34af64,order_created,b536b9c3-171b-448c-9a1d-e3bc3ccb17b0,50.813786,2018-08-01,c6a3cd44-3c73-4cc2-9b0e-773e574baf3a,order_fulfilled,2018-12-03,124
27,0630f0d8-9bc5-4be7-bf6d-5ba93b43f3d9,order_created,b3fd1bc3-d5d3-4b73-85da-ffe956294918,859.918217,2009-11-16,d3841484-49b3-4ddd-b9c9-9ae5b32b42f1,order_fulfilled,2010-03-20,124
28,bcbd6175-d953-45fa-a2f6-ddf1aa2cea9b,order_created,7766939a-fafe-434f-8201-dddc468cde13,813.242594,2017-01-01,a1dcfa6c-7d1a-4ae1-8e75-52e7480e7bdb,order_fulfilled,2017-04-23,112
29,279f58a0-77aa-4332-9bee-3790c97c1f69,order_created,844fbb20-83ee-4d52-b315-6de1c7fe187c,135.501025,2009-08-12,74922895-67fd-490a-8dba-f485437c126b,order_fulfilled,2009-11-21,101
30,8e39a123-2005-4af7-8288-591b37ee0cf3,order_created,1f411826-a338-4dfe-aa9a-f134bd82b1a6,265.942598,2015-02-07,1a8446c3-cedf-4898-a8da-e746ff6848e0,order_fulfilled,2015-07-16,159
31,10604b60-734e-470e-a831-95c51de9ac9a,order_created,8e9519b8-b654-4e43-996f-c4b15c2d05e8,20.454430,2013-06-26,55c62bec-93f1-4853-8457-fd0c2b902db7,order_fulfilled,2013-09-30,96
32,43c637f2-401b-4584-a625-4ec157bad149,order_created,fe44396f-ebe7-42bf-b2a3-6d262d20cdb9,854.059814,2012-05-09,26334354-9da1-4470-a9b7-ae0e446cbad8,order_fulfilled,2012-06-19,41
33,78647595-6cb6-4046-b00b-ad3a8945c646,order_created,29aa32dd-4294-4420-84af-b2981b6172ea,196.137668,2017-06-23,8e426052-5780-481b-849e-43a01249d138,order_fulfilled,2017-08-04,42
34,8b1f0d7f-fd78-415e-8d66-050ca60e1994,order_created,31175471-b322-492e-9574-7a020733ce68,906.125741,2015-10-16,2482881c-f24b-4c7e-9b86-03fd668960b3,order_fulfilled,2015-11-23,38
35,28f96254-85f5-43d4-9fa5-a633ff2db2b6,order_created,2ed4e6da-dece-45ac-8e97-8f5654fc1138,114.413423,2017-08-15,4ed773f3-4ba4-4ac3-be93-e40e9dc6195f,order_fulfilled,2017-10-13,59
36,99a09e8f-2785-4081-83e2-0d845dfbef39,order_created,8ba65434-d7eb-4da7-82f7-1303f5f361b4,191.435305,2010-09-23,07fd7707-fd4f-4359-a1c2-75c453762398,order_fulfilled,2010-12-12,80
37,147fa6ab-3ba7-4b69-8256-6240a1ae01cc,order_created,6a71a40f-965a-4bf9-9d1c-3cc9b599ef64,827.390195,2015-09-12,5b4b3c3c-98aa-403e-871b-d49f60eef9c7,order_fulfilled,2015-09-12,0
38,929c00f1-4ecc-46b4-afad-3095d61aaf73,order_created,7fa13c42-c6a7-4ec8-85db-c511e5a85339,361.447113,2014-08-24,3d218624-1119-4e30-8052-a195da9cb49e,order_fulfilled,2014-08-28,4
39,64e511c3-4082-41f6-9803-b3124688fb05,order_created,49823451-3b2e-4b5b-8003-558b6e489951,446.467817,2013-08-07,275524fa-38f2-4724-810e-2b6413ca2a59,order_fulfilled,2013-11-24,109
40,86bd53dd-24e6-4eaa-9045-44fbb4532bc7,order_created,08723534-377b-4be7-84d9-e4dd32bdb483,919.998421,2008-05-25,20c822ce-f8f0-4318-b217-b64c463150f8,order_fulfilled,2008-06-27,33
41,3751fea4-5a40-436b-b62d-83279d478dbd,order_created,d7051cb2-4a4c-4ddf-afe0-f268792ce620,411.445448,2016-05-13,91066e8d-1626-4de2-9c4f-f3d818d533cb,order_fulfilled,2016-07-06,54
42,8ebdd7e4-19a8-493f-975e-7c5da0aaa9b3,order_created,b5645c5e-7ae9-4563-8c87-16e05949d282,664.979068,2018-12-09,86e70f03-dd4c-49c5-bcb6-c5337e406c6e,order_fulfilled,2018-12-26,17
43,0d3fb3ec-0e81-414d-b469-d655e79b9344,order_created,f3b6a859-528c-44d1-aee3-88dcec0cc90e,569.196461,2018-12-29,31d8c783-f57d-4508-9f4a-5930af9bda6a,order_fulfilled,2018-12-29,0

In [33]:
#Rearranging new dataframe and extracting orders with at least 30 days delay, 
#then reassigning this new data to gt30_df (greater than 30 dataframe)

merged_df.rename(columns= {"created_at_x": "order_date", "created_at_y": "fulfilled_date"}, inplace = True)

del merged_df["event_type_x"]
del merged_df["event_id_x"]
del merged_df["event_id_y"]
del merged_df["event_type_y"]

gt30_df = merged_df.loc[merged_df["delay"] >= 30]
gt30_df

,order_id,amount,order_date,fulfilled_date,delay
1,55846aab-53f6-4aa4-94c8-e63c05c4b579,690.585702,2011-10-16,2011-12-20,65
2,6764d3db-be33-40b5-a738-a8c8e197e97b,442.427812,2014-07-07,2014-12-29,175
3,64e5dfcf-8c96-458d-9cb8-854dab616bea,934.957777,2010-02-06,2010-05-13,96
5,a2662e34-9b64-4168-93d0-f5a0a1be89b0,685.974289,2016-04-23,2016-09-28,158
6,b3b450e9-543d-45f4-ad12-dbbc269ed26c,291.575697,2010-07-24,2011-01-03,163
7,dc957b8a-d153-47ab-9eaa-fa3c8e5d0fa8,552.729193,2014-10-04,2014-12-11,68
8,013f1f27-f0cd-416b-ad6a-533a126523f6,92.058322,2017-02-05,2017-05-29,113
9,92741913-91c1-4968-8a74-d8cd06e995d7,510.871796,2012-06-30,2012-09-01,63
10,fa6afd8c-2eca-468a-863e-0febae8840bf,560.363852,2015-02-20,2015-07-07,137
12,775c1372-4e05-4f61-b828-b5bc03641ceb,745.473292,2011-03-26,2011-08-18,145
13,1a0f349f-34fe-426d-8b6b-24f988ab27ff,61.711721,2015-04-27,2015-08-19,114
14,b220551f-7eab-42e4-b9a8-a1eb585a3774,297.066306,2010-07-24,2010-10-24,92
15,301da4d9-3e83-4126-98b9-60f0dce81dca,141.341280,2017-04-18,2017-07-31,104
17,0cd159b3-e3ae-41ad-bad8-c5415c3ebdfc,731.729933,2018-06-30,2018-11-12,135
18,3e94ecf4-bac0-421e-bcbf-5af592021702,87.396222,2010-09-28,2011-02-19,144
19,68e06b8c-c7eb-4a40-974d-088dd86c95bf,691.589017,2011-11-28,2012-05-12,166
20,32db02ab-ebda-48eb-ad54-c66c6df54ee8,921.851503,2015-03-09,2015-05-29,81
21,9d48ae97-9d31-4cb5-b3b0-486a746e6896,603.256122,2013-05-03,2013-06-22,50
22,c530e896-a711-45a1-a76f-65a85aa89d70,667.981182,2008-01-01,2008-06-09,160
23,09d1ed6a-420f-40a3-983d-57425cd4b439,944.615675,2009-11-30,2010-02-22,84
26,b536b9c3-171b-448c-9a1d-e3bc3ccb17b0,50.813786,2018-08-01,2018-12-03,124
27,b3fd1bc3-d5d3-4b73-85da-ffe956294918,859.918217,2009-11-16,2010-03-20,124
28,7766939a-fafe-434f-8201-dddc468cde13,813.242594,2017-01-01,2017-04-23,112
29,844fbb20-83ee-4d52-b315-6de1c7fe187c,135.501025,2009-08-12,2009-11-21,101
30,1f411826-a338-4dfe-aa9a-f134bd82b1a6,265.942598,2015-02-07,2015-07-16,159
31,8e9519b8-b654-4e43-996f-c4b15c2d05e8,20.454430,2013-06-26,2013-09-30,96
32,fe44396f-ebe7-42bf-b2a3-6d262d20cdb9,854.059814,2012-05-09,2012-06-19,41
33,29aa32dd-4294-4420-84af-b2981b6172ea,196.137668,2017-06-23,2017-08-04,42
34,31175471-b322-492e-9574-7a020733ce68,906.125741,2015-10-16,2015-11-23,38
35,2ed4e6da-dece-45ac-8e97-8f5654fc1138,114.413423,2017-08-15,2017-10-13,59
36,8ba65434-d7eb-4da7-82f7-1303f5f361b4,191.435305,2010-09-23,2010-12-12,80
39,49823451-3b2e-4b5b-8003-558b6e489951,446.467817,2013-08-07,2013-11-24,109
40,08723534-377b-4be7-84d9-e4dd32bdb483,919.998421,2008-05-25,2008-06-27,33
41,d7051cb2-4a4c-4ddf-afe0-f268792ce620,411.445448,2016-05-13,2016-07-06,54

#converting gt30_df to a dictionary (result)

result = gt30_df.to_dict()
result

Question #2

In [9]:
gt30_df["delay"].describe()

count     29.000000
mean     108.931034
std       49.922748
min       31.000000
25%       55.000000
50%      109.000000
75%      156.000000
max      178.000000
Name: delay, dtype: float64

In [34]:
gt30_df["fulfilled_year"] = gt30_df["fulfilled_date"].dt.year
gt30_df["fulfilled_month"] = gt30_df["fulfilled_date"].dt.month
gt30_df

,order_id,amount,order_date,fulfilled_date,delay,fulfilled_year,fulfilled_month
1,55846aab-53f6-4aa4-94c8-e63c05c4b579,690.585702,2011-10-16,2011-12-20,65,2011,12
2,6764d3db-be33-40b5-a738-a8c8e197e97b,442.427812,2014-07-07,2014-12-29,175,2014,12
3,64e5dfcf-8c96-458d-9cb8-854dab616bea,934.957777,2010-02-06,2010-05-13,96,2010,5
5,a2662e34-9b64-4168-93d0-f5a0a1be89b0,685.974289,2016-04-23,2016-09-28,158,2016,9
6,b3b450e9-543d-45f4-ad12-dbbc269ed26c,291.575697,2010-07-24,2011-01-03,163,2011,1
7,dc957b8a-d153-47ab-9eaa-fa3c8e5d0fa8,552.729193,2014-10-04,2014-12-11,68,2014,12
8,013f1f27-f0cd-416b-ad6a-533a126523f6,92.058322,2017-02-05,2017-05-29,113,2017,5
9,92741913-91c1-4968-8a74-d8cd06e995d7,510.871796,2012-06-30,2012-09-01,63,2012,9
10,fa6afd8c-2eca-468a-863e-0febae8840bf,560.363852,2015-02-20,2015-07-07,137,2015,7
12,775c1372-4e05-4f61-b828-b5bc03641ceb,745.473292,2011-03-26,2011-08-18,145,2011,8
13,1a0f349f-34fe-426d-8b6b-24f988ab27ff,61.711721,2015-04-27,2015-08-19,114,2015,8
14,b220551f-7eab-42e4-b9a8-a1eb585a3774,297.066306,2010-07-24,2010-10-24,92,2010,10
15,301da4d9-3e83-4126-98b9-60f0dce81dca,141.341280,2017-04-18,2017-07-31,104,2017,7
17,0cd159b3-e3ae-41ad-bad8-c5415c3ebdfc,731.729933,2018-06-30,2018-11-12,135,2018,11
18,3e94ecf4-bac0-421e-bcbf-5af592021702,87.396222,2010-09-28,2011-02-19,144,2011,2
19,68e06b8c-c7eb-4a40-974d-088dd86c95bf,691.589017,2011-11-28,2012-05-12,166,2012,5
20,32db02ab-ebda-48eb-ad54-c66c6df54ee8,921.851503,2015-03-09,2015-05-29,81,2015,5
21,9d48ae97-9d31-4cb5-b3b0-486a746e6896,603.256122,2013-05-03,2013-06-22,50,2013,6
22,c530e896-a711-45a1-a76f-65a85aa89d70,667.981182,2008-01-01,2008-06-09,160,2008,6
23,09d1ed6a-420f-40a3-983d-57425cd4b439,944.615675,2009-11-30,2010-02-22,84,2010,2
26,b536b9c3-171b-448c-9a1d-e3bc3ccb17b0,50.813786,2018-08-01,2018-12-03,124,2018,12
27,b3fd1bc3-d5d3-4b73-85da-ffe956294918,859.918217,2009-11-16,2010-03-20,124,2010,3
28,7766939a-fafe-434f-8201-dddc468cde13,813.242594,2017-01-01,2017-04-23,112,2017,4
29,844fbb20-83ee-4d52-b315-6de1c7fe187c,135.501025,2009-08-12,2009-11-21,101,2009,11
30,1f411826-a338-4dfe-aa9a-f134bd82b1a6,265.942598,2015-02-07,2015-07-16,159,2015,7
31,8e9519b8-b654-4e43-996f-c4b15c2d05e8,20.454430,2013-06-26,2013-09-30,96,2013,9
32,fe44396f-ebe7-42bf-b2a3-6d262d20cdb9,854.059814,2012-05-09,2012-06-19,41,2012,6
33,29aa32dd-4294-4420-84af-b2981b6172ea,196.137668,2017-06-23,2017-08-04,42,2017,8
34,31175471-b322-492e-9574-7a020733ce68,906.125741,2015-10-16,2015-11-23,38,2015,11
35,2ed4e6da-dece-45ac-8e97-8f5654fc1138,114.413423,2017-08-15,2017-10-13,59,2017,10
36,8ba65434-d7eb-4da7-82f7-1303f5f361b4,191.435305,2010-09-23,2010-12-12,80,2010,12
39,49823451-3b2e-4b5b-8003-558b6e489951,446.467817,2013-08-07,2013-11-24,109,2013,11
40,08723534-377b-4be7-84d9-e4dd32bdb483,919.998421,2008-05-25,2008-06-27,33,2008,6
41,d7051cb2-4a4c-4ddf-afe0-f268792ce620,411.445448,2016-05-13,2016-07-06,54,2016,7

In [35]:
result_2 = gt30_df.groupby(["fulfilled_year", "fulfilled_month"]).agg({"delay": ["mean", "min", "max", "count"]})
result_2

                                delay
                                 mean  min  max count
fulfilled_year fulfilled_month
2008           6                 96.5   33  160     2
2009           11               101.0  101  101     1
2010           2                 84.0   84   84     1
               3                124.0  124  124     1
               5                 96.0   96   96     1
               10                92.0   92   92     1
               12                80.0   80   80     1
2011           1                163.0  163  163     1
               2                144.0  144  144     1
               8                145.0  145  145     1
               12                65.0   65   65     1
2012           5                166.0  166  166     1
               6                 41.0   41   41     1
               9                 63.0   63   63     1
2013           6                 50.0   50   50     1
               9                 96.0   96   96     1
               11               109.0  109  109     1
2014           12               121.5   68  175     2
2015           5                 81.0   81   81     1
               7                148.0  137  159     2
               8                114.0  114  114     1
               11                38.0   38   38     1
2016           7                 54.0   54   54     1
               9                158.0  158  158     1
2017           4                112.0  112  112     1
               5                113.0  113  113     1
               7                104.0  104  104     1
               8                 42.0   42   42     1
               10                59.0   59   59     1
2018           11               135.0  135  135     1
               12               124.0  124  124     1